### ISSUE TITLE
Introducing temporary variables to avoid repeated calculations

### ISSUE THREAD

**Issue by nicheng22** [nyu-cds/hc1924_assignment3#4]
Just as what we've done to simplify the calculation of mag, we can also introduce variables that store the results of m2 * mag and m1 * mag to further improve the performance when updating v1 and v2. For each iteration, the calculation can be reduced to only once instead of three.

**Comment by overwaterland** [comment]
Thank you! I have actually tested the time your way but I find the time barely reduced.
